import React from "react";
import search from '../../Images/search.png'
import select from '../../Images/select.png'
import stand from '../../Images/stand.png'
import './Features.scss'
const Features=()=>{
    return (
      <div className="features-container">
        <div className="feature-detail-container">
          <div className="features">
            <div className="feature-details">
              <div className="img">
               <img src={search}  alt='img'/>
              </div>
              <div className="feature-heading">
                Search
              </div>
              <div className="description">
              Simply add a keyword or a term related to your business in the slogan maker search box. Wait for the magic to happen.
              </div>
            </div>
            <div className="feature-details">
              <div className="img">
               <img src={select} alt='img'/>
              </div>
              <div className="feature-heading"> 
                Select
              </div>
              <div className="description">
              Choose from thousands of options generated by the slogan maker that fit your needs.
              </div>
            </div>
            <div className="feature-details">
              <div className="img">
               <img src={stand} alt='img'/>
              </div>
              <div className="feature-heading">
                Stand out
              </div>
              <div className="description">
              Congrats on your new slogan. It's time to win the world!
              </div>
            </div>
          </div>
        </div>
      </div>
    )
};
export default Features;